Subscription Change Notifications
MelamudMichael/up-client-zenoh-cpp pull request #4
Opened 2024-01-29 20:19 UTC by LinsonI

2024-02-08 10:15 UTC, MelamudMichael commented on include/uprotocol-cpp-ulink-zenoh/usubscription/internal/uSubscriptionClientDb.h
> +            notifyMap_[topic] = func;
check if already exists, return an error if yes

2024-02-08 10:16 UTC, MelamudMichael commented on include/uprotocol-cpp-ulink-zenoh/usubscription/internal/uSubscriptionClientDb.h
> +                return UCode::INTERNAL;
print error

2024-02-09 22:21 UTC, linsonittoop commented
Fixed review comments

2024-02-16 06:08 UTC, MelamudMichael requested changes

2024-02-16 06:08 UTC, MelamudMichael commented on src/zenohUTransport.cpp
>          // if (UCode::OK != getPublisherStatus(uri)) {
why is this commented out?

2024-02-16 06:08 UTC, MelamudMichael commented on include/uprotocol-cpp-ulink-zenoh/usubscription/internal/uSubscriptionClientDb.h
>              // if (!u.SerializeToString(&serUri)) {
why this is commented out?

2024-02-18 06:31 UTC, MelamudMichael requested changes

2024-02-18 06:31 UTC, MelamudMichael commented on include/uprotocol-cpp-ulink-zenoh/usubscription/internal/uSubscriptionClientDb.h
> +            if (str == subUri) {
As you registered the OnRecive for the following URI 
("/core.usubscription/3/subscriptions#Update");

You will always receive message on this specific URI , so this check is not needed.
Instead you need to check the payload , as it is the one that actually contains the URI that you are getting the Update for

2024-02-18 06:31 UTC, MelamudMichael commented on include/uprotocol-cpp-ulink-zenoh/usubscription/internal/uSubscriptionClientDb.h
> +                    notify(update.status());
Please check the return value

2024-02-18 06:31 UTC, MelamudMichael commented on examples/subscription/src/main_subscription.cpp
> +    int init() {
the convention is to use UCode

2024-02-18 06:31 UTC, MelamudMichael commented on examples/subscription/src/main_subscription.cpp
>  using namespace uprotocol::v1;
You are missing the test that will check the actual notification logic.
For example - 
1. send subscription request for a remote topic
2. server returns SUBSCRIBE_PENDING
3. As we dont have remote subscriptions support yet, the server should wait for one second, and send notification SUBSCRIBED (this part should be simulated in the server implementation)

2024-02-20 19:19 UTC, closed without merging